export const ACTION_PRODUCT_DELETE ='ACTION_PRODUCT_DELETE';
export const ACTION_PRODUCT_EDIT ='ACTION_PRODUCT_EDIT';
export const ACTION_PRODUCT_LIST ='ACTION_PRODUCT_LIST';
export const ACTION_PRODUCT_ADD ='ACTION_PRODUCT_ADD';
export const ACTION_PRODUCT_GET_ITEM='ACTION_PRODUCT_GET_ITEM';